language: objective-c
os: osx
osx_image: xcode8.3
cache:
- cocoapods
- pip
before_install:
- gem install --no-rdoc --no-ri 'cocoapods:1.2.1'
- brew update
- brew install clang-format
- brew install swiftlint || brew upgrade swiftlint
- sudo pip install lizard
- pod repo update > /dev/null
- pod install --project-directory=Example
script:
- xcodebuild -scheme "$SCHEME" -workspace "$WORKSPACE" -sdk "$SDK" -destination "$DESTINATION" build test | xcpretty
- pod lib lint --allow-warnings
- ./clang-check.sh
- swiftlint lint --path SKYKitChat
- lizard SKYKitChat/ -C 15 -w -i 0
before_deploy:
- rvm install ruby-2.2.4
- rvm use ruby-2.2.4
- gem install jazzy
- sudo pip install awscli
- sudo pip install https://github.com/SkygearIO/skygear-doc-tools/archive/master.zip
- aws configure set preview.cloudfront true
deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/chat-SDK-iOS
      all_branches: true
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Example/SkyKitChat.xcworkspace
    - SCHEME="SKYKitChat-Example"
    - DESTINATION="OS=10.0,name=iPhone 6S"
    - SDK=iphonesimulator
notifications:
  slack:
    secure: "hbywy0z9plRgggtcmu+mhNug7R4u4P4jYckAyqNJBiiYqq3mwwB0/chis+balqKHmgcxUvbylRQipyvukvsX26eio6rjZWhZgWwg/yZHFkk0MZfvjZsOY9sDTImrizcWB/DE/GiEo2aSOSHOJVcSKim8Axsu3vxPRHA7Ujf2Ng15/IiT0Lc8i8uo0cXUyFQwfhRlS0im9Vk9MV1d2qRdJXjPFYfN/vkIXK3gTPJDVB8FF2bfA0nGGoNjKsZWDYj0WwLPHSucYHavvhxAtCIaL8FFAgdsvQpYTGRe6JKvRdz2FvLlozKX5YwSZ+1HwjlppSgwEqhXXJxBtEMQpjX//2DBEc16JngnXERJJ85JbIaNMmLIu5tJ2GNqhog/lftcezdUHymMmiAZiDxWX+v+7i1TgCP1pOouJd8p/s745hIhOzG/jxcE2gOPH9ob1LzPHsBiNP7t2AbdEBBsLDSZekmDyNK5LAFmDlAhkziIqPL49RRDDpvDRr3Rz7meMNs3MDq2b/8gYn8L8vikUIaFsdcpaLN76ktiOW7QTwzweJKbZjJbc7PrjPebx+l4Ex3cfejhkYPiFx3d8ItOAD4av6Da+stLMyoWPT8uXViCG7uME64emwU2/pS3WiixYZRyqo6XYmha0CmpkxdRoZUsri1PMTq35BvrUneU7C0wnMY="
